### ISSUE TITLE
git 1.5 incompatibility

### ISSUE THREAD

**Issue by erotte** [jbarnette/vlad-git#1]
The Git syntax seems to differ between 1.5x and and 1.6x Versions. 
`{git_cmd} submodule update --init"`

With git 1.5 fails with the following error:

`Usage: /usr/bin/git-submodule [--quiet] [--cached] [add <repo> [-b branch]|status|init|update] [--] [<path>...]`

On my local machine (git 1.6) everything works like a charm.

I unpacked the gem to  my vendor directory an changed 

`"#{git_cmd} submodule update --init"`

to 

`"#{git_cmd} submodule init",`
`"#{git_cmd} submodule update",`

regards,
Eckhard

**Comment by bhoggard** [comment]
Thanks.  I made this fix too and now it's fine.

**Comment by ktheory** [comment]
I made a patch for this change & sent jbarnette a pull request: http://github.com/ktheory/vlad-git/commit/0a098854fdfb0c2c46ba62a1927ed3ee87dc4c01

-Aaron

**Comment by ryanwood** [comment]
The gem needs to be updated to include this fix. It's still broken. :(

**Comment by ktheory** [comment]
Hi Ryan,

I released my own gem to use until the official gem is released.

```
sudo gem install ktheory-vlad-git
```

My gem also fixes the (critical?) bug where old code is released instead of the latest code: http://github.com/jbarnette/vlad-git/issues#issue/3 

To make sure the right "vlad-git" is required, either specify
    gem "ktheory-vlad-git"
in your deploy.rb, or uninstall the vlad-git gem.

**Comment by ktheory** [comment]
Fixed in http://github.com/jbarnette/vlad-git/commit/f6f98fd994a12848b619fd5a82df355b348ac69b
